//
// Created by Fonzy on 4/23/2023.
//

#ifndef SANCHOPROJ_DEFINITIONS_H
#define SANCHOPROJ_DEFINITIONS_H

#define MENU_OPTION_MAX 3
#define STUDENTS_MAX 100
#define STUDENT_NAME_MAX 50
#define PASSWORD_MAX 20
#define COURSES_MAX 8
#define COURSES_TITLE_MAX 25

#define DEGREE_PROGRAM "BS CPE"
#define STUDENT_ADDRESS "Imus, Cavite"
#define STUDENT_PHONE "123456789"
#define PRESENT_ADDRESS "Malate, Manila"

#endif //SANCHOPROJ_DEFINITIONS_H
