//
// Created by Fonzy on 4/23/2023.
//

#ifndef SANCHOPROJ_DEFINITIONS_H
#define SANCHOPROJ_DEFINITIONS_H

#define MENU_OPTION_MAX 3
#define STUDENTS_MAX 100
#define STUDENT_NAME_MAX 50
#define PASSWORD_MAX 20
#define COURSES_MAX 8
#define COURSES_TITLE_MAX 15

#endif //SANCHOPROJ_DEFINITIONS_H
